### ISSUE TITLE
[Bug] Can't save profile 

### ISSUE THREAD

**Issue by RiccardoM** [vaiainnovations/scripta#6]
## Description 
Trying to save a profile for the first time, it results in the following error being thrown while clicking the _Save_ button (even before signing the transaction, which is never received into DPM):

```
TypeError: Cannot read properties of null (reading 'dtag')
    at V (profile-904db2fc.mjs:1:3256)
    at callWithErrorHandling (entry-4c4d9563.mjs:1:18618)
    at callWithAsyncErrorHandling (entry-4c4d9563.mjs:1:18754)
    at HTMLButtonElement.St (entry-4c4d9563.mjs:1:93123)
```

My address is the following: [desmos1vxe0qadrgpg52zk03k5r29wd9jt59ej664t2yl](https://morpheus.desmos.network/accounts/desmos1vxe0qadrgpg52zk03k5r29wd9jt59ej664t2yl)

Screenshot of the input data:

![screenshot-beta scripta network-2022 08 03-11_40_26](https://user-images.githubusercontent.com/9119016/182577840-f1514c68-1d5e-415e-8e94-8eb041ef4df5.png)

**Comment by RiccardoM** [comment]
This is no longer present. I think this can be closed now
